terraform {
  required_version = ">= 1.5.0"

  # Backend is configured at init via -backend-config (see infra/terraform/.backend/*.hcl
  # generated by `make terraform-backend-config` from `.env-local`).
  backend "s3" {}

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.4"
    }
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = var.project
      Environment = var.environment
      ManagedBy   = "terraform"
    }
  }
}
